name: "Apply PR conflict label"

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [synchronize]

permissions:
  pull-requests: write
  issues: write

jobs:
  apply-conflict-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PRs have conflicts
        uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: "Has conflicts"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_RETRIES: 5
          WAIT_MS: 5000