name: apply-conflict-label

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  label-merge-conflicts:
    runs-on: ubuntu-latest

    # (Optional but recommended) repeat at job-level to avoid any override
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Check if PRs have conflicts
        uses: eps1lon/actions-label-merge-conflict@v3
        with:
          dirtyLabel: "Action required: fix conflict"
          removeOnDirtyLabel: "READY TO MERGE"
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          commentOnDirty: "This pull request has conflicts, please resolve those before we can evaluate the pull request."
          commentOnClean: "Conflicts have been resolved. A maintainer will review the pull request shortly."
